# Generated by Django 4.2.4 on 2023-10-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerceapp', '0002_product_remove_contact_contact_id_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategorey',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorey',
            new_name='subcategory',
        ),
    ]
